#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Tue Jun 21 10:17:16 2005
"""Application defined for testing purpose"""

from solipsis.util.wxutils import _

from solipsis.services.profile.editor.view import EditorView
from solipsis.services.profile.gui.EditorFrame import EditorFrame
from solipsis.services.profile.gui.base_gui import BaseGUI, get_options

class EditorApp(BaseGUI):
    """Top-level class of GUI: application"""
    def __init__(self, options, *args):
        BaseGUI.__init__(self, options, *args)
        
    def OnInit(self):
        """overrides"""
        BaseGUI.OnInit(self)
        self.main_window = EditorFrame(self.options, None, -1,
                                       _("Profile Editor"),
                                       plugin=self.plugin)
        self.SetTopWindow(self.main_window)
        self.main_window.Show()
        # set up facade
        self.facade.add_view(EditorView(self.facade._desc,
                                        self.main_window))
        self.main_window.on_change_facade()
        return 1
    
def run():
    """launch editor of profile"""
    options = get_options()
    editor = EditorApp(options, 0)
    editor.MainLoop()
    
if __name__ == "__main__":
    run()
