#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Tue Jun 21 11:01:29 2005

from solipsis.util.wxutils import _
from solipsis.services.profile.filter_facade import create_filter_facade
from solipsis.services.profile.view import FilterView
from solipsis.services.profile.gui.FilterFrame import FilterFrame
from solipsis.services.profile.gui.base_gui import BaseGUI, get_options

class FilterApp(BaseGUI):
    """Top-level class of GUI: application"""
    def __init__(self, options, *args):
        BaseGUI.__init__(self, options, *args)
        
    def OnInit(self):
        BaseGUI.OnInit(self)
        filter_facade = create_filter_facade("manu")
        filter_facade.load()
        self.main_window = FilterFrame(self.options, None, -1, "")
        self.SetTopWindow(self.main_window)
        self.main_window.Show()
        # set up facade
        filter_facade.add_view(FilterView(filter_facade._desc,
                                          self.main_window))
        return 1

# end of class FilterApp

def run():
    """launch editor of profile"""
    options = get_options()
    filter = FilterApp(options, 0)
    filter.MainLoop()
    
if __name__ == "__main__":
    run()
