#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Tue Jun 21 11:01:29 2005

import wx

from solipsis.util.wxutils import _
from solipsis.services.profile.facade import create_facade, create_filter_facade
from solipsis.services.profile.view import FilterView
from solipsis.services.profile.gui.FilterFrame import FilterFrame

class FilterApp(wx.App):
    """Top-level class of GUI: application"""
    def __init__(self, options, *args):
        self.options = options
        wx.App.__init__(self, *args)
        
    def OnInit(self):
        facade = create_facade("manu")
        filter_facade = create_filter_facade("manu")
        filter_facade.load()
        # set up GUI
        wx.InitAllImageHandlers()
        filter_frame = FilterFrame(self.options, None, -1, "")
        self.SetTopWindow(filter_frame)
        filter_frame.Show()
        # set up facade
        filter_facade.add_view(FilterView(filter_facade._desc, filter_frame))
        return 1

# end of class FilterApp

def run():
    """launch editor of profile"""
    import gettext
    gettext.install("filter") # replace with the appropriate catalog name
    # set options
    options = {}
    options["standalone"] = True
    # launch gui
    filter = FilterApp(options, 0)
    filter.MainLoop()

    
if __name__ == "__main__":
    run()
