# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Mon Apr 25 16:31:38 2005

import wx

from solipsis.util.wxutils import _
from solipsis.util.wxutils import GetStockToolbarBitmap as TB

# begin wxGlade: dependencies
# end wxGlade

# ID allocation
_ids = [
    "TOOL_ADD_BOOKMARK",
    "TOOL_DEL_BOOKMARK",
]
for _id in _ids:
    locals()[_id] = wx.NewId()


class BookmarksDialog(wx.Frame):
    def __init__(self, world, bookmarks, *args, **kwds):
        self.world = world
        self.bookmarks = bookmarks

        # begin wxGlade: BookmarksDialog.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)
        
        # Tool Bar
        self.toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT|wx.TB_HORZ_LAYOUT|wx.TB_HORZ_TEXT)
        self.SetToolBar(self.toolbar)
        self.toolbar.AddLabelTool(TOOL_ADD_BOOKMARK, _("Add bookmark"), (TB(wx.ART_ADD_BOOKMARK)), wx.NullBitmap, wx.ITEM_NORMAL, _("Bookmark a node"), "")
        self.toolbar.AddLabelTool(TOOL_DEL_BOOKMARK, _("Remove"), (TB(wx.ART_DEL_BOOKMARK)), wx.NullBitmap, wx.ITEM_NORMAL, _("Remove selected bookmark"), "")
        # Tool Bar end
        self.list_ctrl = wx.ListCtrl(self.panel_1, -1, style=wx.LC_REPORT|wx.LC_NO_HEADER|wx.SUNKEN_BORDER)
        self.button_close = wx.Button(self.panel_1, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.OnAddBookmark, id=TOOL_ADD_BOOKMARK)
        self.Bind(wx.EVT_TOOL, self.OnDelBookmark, id=TOOL_DEL_BOOKMARK)
        self.Bind(wx.EVT_BUTTON, self.OnClose, id=wx.ID_CLOSE)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BookmarksDialog.__set_properties
        self.SetTitle(_("Bookmarks"))
        self.SetMinSize((309, 223))
        self.toolbar.Realize()
        self.button_close.SetDefault()
        # end wxGlade
        self.toolbar.EnableTool(TOOL_DEL_BOOKMARK, False)

    def __do_layout(self):
        # begin wxGlade: BookmarksDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.list_ctrl, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_close, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        self.panel_1.SetAutoLayout(True)
        self.panel_1.SetSizer(sizer_2)
        sizer_2.Fit(self.panel_1)
        sizer_2.SetSizeHints(self.panel_1)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    #
    # Event handlers
    #

    def OnAddBookmark(self, event): # wxGlade: BookmarksDialog.<event_handler>
        print "Add Bookmark"
        event.Skip()

    def OnDelBookmark(self, event): # wxGlade: BookmarksDialog.<event_handler>
        print "Del Bookmark"
        event.Skip()

    def OnClose(self, event): # wxGlade: BookmarksDialog.<event_handler>
        self.Hide()
        event.Skip()

# end of class BookmarksDialog
