# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Mon Aug 29 15:55:31 2005

import wx

from solipsis.util.wxutils import _
from solipsis.util.urls import SolipsisURL

# begin wxGlade: dependencies
# end wxGlade

class BookmarkPropsDialog(wx.Dialog):
    def __init__(self, peer, *args, **kwds):
        self.peer = peer

        # begin wxGlade: BookmarkPropsDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_name = wx.StaticText(self, -1, _("Name :"))
        self.text_ctrl_name = wx.TextCtrl(self, -1, "")
        self.label_url = wx.StaticText(self, -1, _("Address :"))
        self.value_url = wx.StaticText(self, -1, "")
        self.label_id = wx.StaticText(self, -1, _("Node ID :"))
        self.value_id = wx.StaticText(self, -1, "")
        self.button_close = wx.Button(self, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnClose, id=wx.ID_CLOSE)
        # end wxGlade

        self.Bind(wx.EVT_CLOSE, self.OnClose)

        # Initialize UI values
        self.text_ctrl_name.SetValue(self.peer.pseudo)
        self.value_url.SetLabel(self.peer.address.GetURL().ToString())
        self.value_id.SetLabel(self.peer.id_)
        self.SetTitle(_("Properties for %s") % self.peer.pseudo.strip())
        self._UpdateUI()

    def __set_properties(self):
        # begin wxGlade: BookmarkPropsDialog.__set_properties
        self.button_close.SetDefault()
        # end wxGlade

#         bold_fields = [self.label_name, self.label_url, self.label_id]
        bold_fields = [self.label_name, self.label_url]
        for f in bold_fields:
            font = f.GetFont()
            font.SetWeight(wx.BOLD)
            f.SetFont(font)

    def __do_layout(self):
        # begin wxGlade: BookmarkPropsDialog.__do_layout
        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 2, 2)
        grid_sizer_1.Add(self.label_name, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        grid_sizer_1.Add(self.text_ctrl_name, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 3)
        grid_sizer_1.Add(self.label_url, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        grid_sizer_1.Add(self.value_url, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        grid_sizer_1.Add(self.label_id, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 3)
        grid_sizer_1.Add(self.value_id, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 3)
        grid_sizer_1.AddGrowableCol(1)
        sizer_19.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_19.Add(self.button_close, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 3)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_19)
        sizer_19.Fit(self)
        sizer_19.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade


    #
    # Event handlers
    #
    def OnClose(self, event): # wxGlade: BookmarkPropsDialog.<event_handler>
        if self._Validate():
            self._Apply()
            self.EndModal(wx.ID_OK)
        else:
            dialog = wx.MessageDialog(self,
                message=_("Please enter a name for this bookmark."),
                caption=_("Error"),
                style=wx.OK | wx.ICON_ERROR)
            dialog.ShowModal()


    #
    # Helpers
    #
    def _UpdateUI(self):
        # Adapt dialog size
        self.Layout()
        self.SetSize(self.GetBestVirtualSize())

    def _Validate(self):
        name = self.text_ctrl_name.GetValue().strip()
        if not name:
            return False
        return True

    def _Apply(self):
        name = self.text_ctrl_name.GetValue().strip()
        self.peer.pseudo = name


# end of class BookmarkPropsDialog
