# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Tue May 17 15:43:43 2005

import wx

from solipsis.util.wxutils import _

from ConnectionTypeDialog import ConnectionTypeDialog

# begin wxGlade: dependencies
# end wxGlade

class ConnectDialog(wx.Dialog):
    def __init__(self, config_data, *args, **kwds):
        self.config_data = config_data

        # begin wxGlade: ConnectDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.sizer_5_staticbox = wx.StaticBox(self, -1, _("Connection type"))
        self.label_pseudo = wx.StaticText(self, -1, _("Name or pseudo"))
        self.text_ctrl_pseudo = wx.TextCtrl(self, -1, "")
        self.label_conntype = wx.StaticText(self, -1, _("label_conntype"))
        self.button_change_conntype = wx.Button(self, -1, _("Change"))
        self.button_ok = wx.Button(self, wx.ID_OK, "")
        self.button_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.OnPseudoChanged, self.text_ctrl_pseudo)
        self.Bind(wx.EVT_BUTTON, self.OnChangeConnType, self.button_change_conntype)
        self.Bind(wx.EVT_BUTTON, self.OnOk, id=wx.ID_OK)
        self.Bind(wx.EVT_BUTTON, self.OnCancel, id=wx.ID_CANCEL)
        # end wxGlade

        self.text_ctrl_pseudo.SetValue(config_data.pseudo)
        self._UpdateUI()

    def __set_properties(self):
        # begin wxGlade: ConnectDialog.__set_properties
        self.SetTitle(_("Connect to Solipsis"))
        self.text_ctrl_pseudo.SetFocus()
        self.button_ok.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConnectDialog.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.VERTICAL)
        sizer_3.Add(self.label_pseudo, 0, wx.ALL, 3)
        sizer_3.Add(self.text_ctrl_pseudo, 0, wx.ALL|wx.EXPAND, 3)
        sizer_5.Add(self.label_conntype, 0, wx.ALL|wx.EXPAND, 3)
        sizer_5.Add(self.button_change_conntype, 0, wx.ALL|wx.ALIGN_RIGHT, 3)
        sizer_3.Add(sizer_5, 0, wx.ALL|wx.EXPAND, 4)
        sizer_4.Add(self.button_ok, 0, wx.ALL|wx.ALIGN_BOTTOM, 3)
        sizer_4.Add(self.button_cancel, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 3)
        sizer_3.Add(sizer_4, 1, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        sizer_3.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    #
    # Event handlers
    #
    def OnPseudoChanged(self, event): # wxGlade: ConnectDialog.<event_handler>
        self._UpdateUI()

    def OnChangeConnType(self, event): # wxGlade: ConnectDialog.<event_handler>
        dialog = ConnectionTypeDialog(self.config_data, parent=self) 
        dialog.ShowModal()
        self._UpdateUI()

    def OnOk(self, event): # wxGlade: ConnectDialog.<event_handler>
        if self._Validate():
            self._Apply()
            self.EndModal(wx.ID_OK)

    def OnCancel(self, event): # wxGlade: ConnectDialog.<event_handler>
        self.EndModal(wx.ID_CANCEL)

    #
    # Private methods
    #
    def _ValidatePseudo(self):
        return self.text_ctrl_pseudo.GetValue().strip() != ""

    def _Validate(self):
        return self._ValidatePseudo()

    def _UpdateUI(self):
        # Display proper textual information about connection type
        if self.config_data.connection_type == 'local':
            conntype_text = _("A dedicated Solipsis node will be launched.")
        else:
            conntype_text = _("A remote Solipsis node will be contacted\nat the following address: %s.") \
                % ("%s:%d" % (self.config_data.host, self.config_data.port))
        self.label_conntype.SetLabel(conntype_text)
        # Enable the "ok" button if the form is properly filled
        if self._Validate():
            self.button_ok.Enable()
        else:
            self.button_ok.Disable()
        # Adapt dialog size
        self.Layout()
        self.SetSize(self.GetBestVirtualSize())
    
    def _Apply(self):
        self.config_data.pseudo = self.text_ctrl_pseudo.GetValue()

# end of class ConnectDialog
