#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Tue Mar 22 14:29:09 2005

import wx
from ProfileFrame import ProfileFrame
from solipsis.services.profile.facade import get_facade
from solipsis.services.profile.document import CacheDocument, FileDocument
from solipsis.services.profile.view import GuiView

if __name__ == "__main__":
    #set up GUI
    import gettext
    gettext.install("app") # replace with the appropriate catalog name
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    profile_frame = ProfileFrame(None, -1, "")

    #set up facade
    facade = get_facade()
    file_doc = FileDocument()
    file_doc.load()
    cache_doc = CacheDocument()
    cache_doc.import_document(file_doc)
    view = GuiView(cache_doc, profile_frame)
    facade.add_document(file_doc)
    facade.add_document(cache_doc)
    facade.add_view(view)

    #launch gui
    app.SetTopWindow(profile_frame)
    profile_frame.Show()
    app.MainLoop()
