#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Tue Mar 22 14:29:09 2005

import wx
from ProfileFrame import ProfileFrame

if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    profile_frame = ProfileFrame(None, -1, "")
    app.SetTopWindow(profile_frame)
    profile_frame.Show()
    app.MainLoop()
