# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Fri May 27 17:40:42 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class BlogDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BlogDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.blog_sizer_staticbox = wx.StaticBox(self, -1, _("Peer's Blog"))
        self.blog_panel = BlogPanel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BlogDialog.__set_properties
        self.SetTitle(_("Peer's Blog"))
        self.SetSize((460, 410))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BlogDialog.__do_layout
        blog_sizer = wx.StaticBoxSizer(self.blog_sizer_staticbox, wx.VERTICAL)
        blog_sizer.Add(self.blog_panel, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(blog_sizer)
        self.Layout()
        # end wxGlade

# end of class BlogDialog


