# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.4 on Fri Mar 18 17:46:49 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class InfoPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: InfoPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.photo_button = wx.BitmapButton(self, -1, wx.Bitmap("/home/emb/svn/solipsis/trunk/main/solipsis/services/profile/images/question_mark.gif", wx.BITMAP_TYPE_ANY))
        self.title_lbl = wx.StaticText(self, -1, _("Title: "))
        self.title_balue = wx.ComboBox(self, -1, choices=[_("Mr"), _("Mrs"), _("Ms")], style=wx.CB_DROPDOWN)
        self.firstname_lbl = wx.StaticText(self, -1, _("First Name: "))
        self.firstname_value = wx.TextCtrl(self, -1, "")
        self.lastname_lbl = wx.StaticText(self, -1, _("Last Name: "))
        self.lastname_value = wx.TextCtrl(self, -1, "")
        self.nickname_lbl = wx.StaticText(self, -1, _("Nickname: "))
        self.nickname_value = wx.TextCtrl(self, -1, "")
        self.email_lbl = wx.StaticText(self, -1, _("E-mail: "))
        self.email_value = wx.TextCtrl(self, -1, "")
        self.homepage_lbl = wx.StaticText(self, -1, _("Homepage: "))
        self.homepage_value = wx.TextCtrl(self, -1, "")
        self.phone_lbl = wx.StaticText(self, -1, _("Phone: "))
        self.phone_value = wx.TextCtrl(self, -1, "")
        self.file_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.addfile_button = wx.Button(self, -1, _("Add Files..."))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: InfoPanel.__set_properties
        self.SetSize((300, 364))
        self.photo_button.SetSize(self.photo_button.GetBestSize())
        self.title_balue.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: InfoPanel.__do_layout
        info_sizer = wx.FlexGridSizer(1, 2, 0, 0)
        rightinfo_sizer = wx.BoxSizer(wx.VERTICAL)
        leftinfo_sizer = wx.BoxSizer(wx.VERTICAL)
        desc_sizer = wx.GridSizer(7, 2, 0, 0)
        leftinfo_sizer.Add(self.photo_button, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.title_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.title_balue, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.firstname_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.firstname_value, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.lastname_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.lastname_value, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.nickname_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.nickname_value, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.email_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.email_value, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.homepage_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.homepage_value, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.phone_lbl, 0, wx.FIXED_MINSIZE, 0)
        desc_sizer.Add(self.phone_value, 0, wx.FIXED_MINSIZE, 0)
        leftinfo_sizer.Add(desc_sizer, 0, wx.EXPAND, 0)
        info_sizer.Add(leftinfo_sizer, 1, wx.EXPAND, 0)
        rightinfo_sizer.Add(self.file_list, 1, wx.EXPAND, 0)
        rightinfo_sizer.Add(self.addfile_button, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        info_sizer.Add(rightinfo_sizer, 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(info_sizer)
        info_sizer.AddGrowableRow(0)
        info_sizer.AddGrowableCol(1)
        # end wxGlade

# end of class InfoPanel


