# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Thu Jul  7 18:39:33 2005

import wx
import sys

from solipsis.util.wxutils import _
from solipsis.util.uiproxy import UIProxyReceiver
from solipsis.services.profile.gui.MatchPanel import MatchPanel
from solipsis.services.profile.view import HtmlView

# begin wxGlade: dependencies
# end wxGlade

class MatchDialog(wx.Dialog, UIProxyReceiver):
    def __init__(self, parent, id, plugin=None, **kwds):
        UIProxyReceiver.__init__(self)
        self.plugin = plugin
        args = (parent, id)
        # begin wxGlade: MatchDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.matched_panel = MatchPanel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def set_page(self, (peer_desc, matches)):
        if not matches:
            return
        self.SetTitle("%s's %s"% (peer_desc.pseudo, _("Matches")))
        # preview
        view = HtmlView(peer_desc)
        self.matched_panel.match_preview.SetPage(view.get_view())
        # fill list
        matches_list = self.matched_panel.matches_list
        matches_list.DeleteAllItems()
        for filter_value in matches:
            index = matches_list.InsertStringItem(sys.maxint, filter_value._name)
            matches_list.SetStringItem(index, 1, filter_value._found)
            matches_list.SetStringItem(index, 2, filter_value.description)
        self.Show()

    def __set_properties(self):
        # begin wxGlade: MatchDialog.__set_properties
        self.SetTitle(_("Matches"))
        self.SetSize((460, 410))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MatchDialog.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.matched_panel, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class MatchDialog


