# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Thu Jul  7 18:38:50 2005

import wx

from solipsis.util.wxutils import _
from solipsis.services.profile.gui.PreviewPanel import MyHtmlWindow

# begin wxGlade: dependencies
# end wxGlade

class MatchPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MatchPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.list_sizer_staticbox = wx.StaticBox(self, -1, _("Matches"))
        self.matches_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.match_preview = MyHtmlWindow(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.PopulateList()
        self.bind_controls()

    def PopulateList(self):
        self.matches_list.InsertColumn(0, _("Name"))
        self.matches_list.InsertColumn(1, _("Match"))
        self.matches_list.InsertColumn(2, _("filter"))
        self.matches_list.SetColumnWidth(0, 100)
        self.matches_list.SetColumnWidth(1, 200)
        self.matches_list.SetColumnWidth(1, 100)

    # EVENTS
    
    def bind_controls(self):
        """bind all controls with facade"""
        pass

    def __set_properties(self):
        # begin wxGlade: MatchPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MatchPanel.__do_layout
        match_sizer = wx.BoxSizer(wx.VERTICAL)
        list_sizer = wx.StaticBoxSizer(self.list_sizer_staticbox, wx.VERTICAL)
        list_sizer.Add(self.matches_list, 1, wx.EXPAND, 0)
        match_sizer.Add(list_sizer, 1, wx.EXPAND, 0)
        match_sizer.Add(self.match_preview, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(match_sizer)
        match_sizer.Fit(self)
        match_sizer.SetSizeHints(self)
        # end wxGlade

# end of class MatchPanel


