# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Tue Jun 21 11:01:29 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class PersonalFilterPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PersonalFilterPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.p_action_sizer_staticbox = wx.StaticBox(self, -1, _("Specify here a filter to use for a given keyword"))
        self.identity_sizer_staticbox = wx.StaticBox(self, -1, _("Identity"))
        self.genre_checkbox = wx.CheckBox(self, -1, "")
        self.title_value = wx.ComboBox(self, -1, choices=["", _("Mr"), _("Mrs"), _("Ms")], style=wx.CB_DROPDOWN|wx.CB_SIMPLE|wx.CB_READONLY)
        self.firstname_checkbox = wx.CheckBox(self, -1, "")
        self.firstname_value = wx.TextCtrl(self, -1, _("First name"))
        self.lastname_checkbox = wx.CheckBox(self, -1, "")
        self.lastname_value = wx.TextCtrl(self, -1, _("Last Name"))
        self.pseudo_checkbox = wx.CheckBox(self, -1, _("Pseudo: "))
        self.nickname_value = wx.TextCtrl(self, -1, "")
        self.mail_checkbox = wx.CheckBox(self, -1, _("E-Mail: "))
        self.email_value = wx.TextCtrl(self, -1, "")
        self.p_key_value = wx.TextCtrl(self, -1, _("favorite book"))
        self.p_filter_value = wx.TextCtrl(self, -1, _("*Potter*"))
        self.add_p_filter_button = wx.BitmapButton(self, -1, wx.Bitmap(ADD_CUSTOM(),wx.BITMAP_TYPE_ANY))
        self.del_p_filter_button = wx.BitmapButton(self, -1, wx.Bitmap(DEL_CUSTOM(),wx.BITMAP_TYPE_ANY))
        self.p_filters_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.LC_SORT_ASCENDING|wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PersonalFilterPanel.__set_properties
        self.title_value.SetSelection(0)
        self.nickname_value.SetToolTipString(_("How you appear to other peers"))
        self.nickname_value.Enable(False)
        self.add_p_filter_button.SetSize(self.add_p_filter_button.GetBestSize())
        self.del_p_filter_button.SetSize(self.del_p_filter_button.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PersonalFilterPanel.__do_layout
        p_filter_sizer = wx.FlexGridSizer(3, 1, 0, 0)
        p_action_sizer = wx.StaticBoxSizer(self.p_action_sizer_staticbox, wx.HORIZONTAL)
        identity_sizer = wx.StaticBoxSizer(self.identity_sizer_staticbox, wx.VERTICAL)
        contact_sizer = wx.FlexGridSizer(3, 2, 3, 0)
        name_sizer = wx.FlexGridSizer(1, 6, 3, 3)
        name_sizer.Add(self.genre_checkbox, 0, wx.ADJUST_MINSIZE, 0)
        name_sizer.Add(self.title_value, 0, wx.FIXED_MINSIZE, 0)
        name_sizer.Add(self.firstname_checkbox, 0, wx.ADJUST_MINSIZE, 0)
        name_sizer.Add(self.firstname_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        name_sizer.Add(self.lastname_checkbox, 0, wx.ADJUST_MINSIZE, 0)
        name_sizer.Add(self.lastname_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        name_sizer.AddGrowableCol(3)
        name_sizer.AddGrowableCol(5)
        identity_sizer.Add(name_sizer, 0, wx.EXPAND, 0)
        contact_sizer.Add(self.pseudo_checkbox, 0, wx.ADJUST_MINSIZE, 0)
        contact_sizer.Add(self.nickname_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        contact_sizer.Add(self.mail_checkbox, 0, wx.ADJUST_MINSIZE, 0)
        contact_sizer.Add(self.email_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        contact_sizer.AddGrowableCol(1)
        identity_sizer.Add(contact_sizer, 0, wx.TOP|wx.EXPAND, 3)
        p_filter_sizer.Add(identity_sizer, 0, wx.EXPAND, 0)
        p_action_sizer.Add(self.p_key_value, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 3)
        p_action_sizer.Add(self.p_filter_value, 1, wx.ALL|wx.EXPAND|wx.FIXED_MINSIZE, 3)
        p_action_sizer.Add(self.add_p_filter_button, 0, wx.LEFT|wx.FIXED_MINSIZE, 3)
        p_action_sizer.Add(self.del_p_filter_button, 0, wx.FIXED_MINSIZE, 0)
        p_filter_sizer.Add(p_action_sizer, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 3)
        p_filter_sizer.Add(self.p_filters_list, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(p_filter_sizer)
        p_filter_sizer.Fit(self)
        p_filter_sizer.SetSizeHints(self)
        p_filter_sizer.AddGrowableRow(2)
        p_filter_sizer.AddGrowableCol(0)
        # end wxGlade

# end of class PersonalFilterPanel


