# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Tue Mar 22 11:28:12 2005

import wx, wx.lib.editor

# begin wxGlade: dependencies
# end wxGlade

class PersonalPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PersonalPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.address_sizer_staticbox = wx.StaticBox(self, -1, _("Address"))
        self.description_sizer_staticbox = wx.StaticBox(self, -1, _("Description"))
        self.identity_sizer_staticbox = wx.StaticBox(self, -1, _("Identity"))
        self.title_value = wx.ComboBox(self, -1, choices=[_("Mr"), _("Mrs"), _("Ms")], style=wx.CB_DROPDOWN)
        self.firstname_value = wx.TextCtrl(self, -1, _("First name"))
        self.lastname_value = wx.TextCtrl(self, -1, _("Last Name"))
        self.nickname_lbl = wx.StaticText(self, -1, _("Pseudo: "))
        self.nickname_value = wx.TextCtrl(self, -1, "")
        self.email_lbl = wx.StaticText(self, -1, _("E-mail: "))
        self.email_value = wx.TextCtrl(self, -1, "")
        self.birthday_lbl = wx.StaticText(self, -1, _("Birthday: "))
        self.birthday_value = wx.TextCtrl(self, -1, _("dd/mm/yyyy"))
        self.language_lbl = wx.StaticText(self, -1, _("Language: "))
        self.language_value = wx.ComboBox(self, -1, choices=[_("French"), _("English")], style=wx.CB_DROPDOWN|wx.CB_SORT)
        self.photo_button = wx.BitmapButton(self, -1, wx.Bitmap("/home/emb/svn/solipsis/trunk/main/solipsis/services/profile/images/question_mark.gif", wx.BITMAP_TYPE_ANY))
        self.road_value = wx.TextCtrl(self, -1, _("Road"))
        self.postcode_value = wx.TextCtrl(self, -1, _("Postcode"))
        self.city_value = wx.TextCtrl(self, -1, _("City"))
        self.country_value = wx.TextCtrl(self, -1, _("Country"))
        self.description_value = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_PROCESS_TAB|wx.TE_MULTILINE|wx.HSCROLL|wx.TE_RICH2|wx.TE_LINEWRAP)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PersonalPanel.__set_properties
        self.title_value.SetSelection(0)
        self.nickname_value.SetToolTipString(_("How you appear to other peers"))
        self.language_value.SetSelection(0)
        self.photo_button.SetSize(self.photo_button.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PersonalPanel.__do_layout
        personal_sizer = wx.FlexGridSizer(2, 1, 0, 0)
        description_sizer = wx.StaticBoxSizer(self.description_sizer_staticbox, wx.HORIZONTAL)
        info_sizer = wx.FlexGridSizer(2, 2, 0, 0)
        address_sizer = wx.StaticBoxSizer(self.address_sizer_staticbox, wx.VERTICAL)
        city_sizer = wx.FlexGridSizer(1, 2, 3, 3)
        identity_sizer = wx.StaticBoxSizer(self.identity_sizer_staticbox, wx.VERTICAL)
        detail_sizer = wx.FlexGridSizer(1, 4, 0, 3)
        contact_sizer = wx.FlexGridSizer(3, 2, 3, 0)
        name_sizer = wx.FlexGridSizer(1, 3, 3, 3)
        name_sizer.Add(self.title_value, 0, wx.FIXED_MINSIZE, 0)
        name_sizer.Add(self.firstname_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        name_sizer.Add(self.lastname_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        name_sizer.AddGrowableCol(1)
        name_sizer.AddGrowableCol(2)
        identity_sizer.Add(name_sizer, 0, wx.EXPAND, 0)
        contact_sizer.Add(self.nickname_lbl, 0, wx.FIXED_MINSIZE, 0)
        contact_sizer.Add(self.nickname_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        contact_sizer.Add(self.email_lbl, 0, wx.FIXED_MINSIZE, 0)
        contact_sizer.Add(self.email_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        contact_sizer.AddGrowableCol(1)
        identity_sizer.Add(contact_sizer, 0, wx.TOP|wx.EXPAND, 3)
        detail_sizer.Add(self.birthday_lbl, 0, wx.FIXED_MINSIZE, 0)
        detail_sizer.Add(self.birthday_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        detail_sizer.Add(self.language_lbl, 0, wx.FIXED_MINSIZE, 0)
        detail_sizer.Add(self.language_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        detail_sizer.AddGrowableCol(1)
        detail_sizer.AddGrowableCol(3)
        identity_sizer.Add(detail_sizer, 1, wx.TOP|wx.EXPAND, 3)
        info_sizer.Add(identity_sizer, 1, wx.EXPAND, 0)
        info_sizer.Add(self.photo_button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.FIXED_MINSIZE, 3)
        address_sizer.Add(self.road_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        city_sizer.Add(self.postcode_value, 0, wx.FIXED_MINSIZE, 0)
        city_sizer.Add(self.city_value, 0, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        city_sizer.AddGrowableCol(1)
        address_sizer.Add(city_sizer, 1, wx.TOP|wx.EXPAND, 3)
        address_sizer.Add(self.country_value, 0, wx.TOP|wx.ALIGN_RIGHT|wx.FIXED_MINSIZE, 3)
        info_sizer.Add(address_sizer, 1, wx.EXPAND, 0)
        info_sizer.Add((20, 20), 0, wx.FIXED_MINSIZE, 0)
        info_sizer.AddGrowableCol(0)
        personal_sizer.Add(info_sizer, 0, wx.ALL|wx.EXPAND, 3)
        description_sizer.Add(self.description_value, 1, wx.EXPAND|wx.FIXED_MINSIZE, 0)
        personal_sizer.Add(description_sizer, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(personal_sizer)
        personal_sizer.Fit(self)
        personal_sizer.SetSizeHints(self)
        personal_sizer.AddGrowableRow(1)
        personal_sizer.AddGrowableCol(0)
        # end wxGlade

# end of class PersonalPanel


