# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.4 on Fri Mar 18 15:52:40 2005

import wx

# begin wxGlade: dependencies
# end wxGlade

class ProfileFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ProfileFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.profile_book = wx.Notebook(self, -1, style=0)
        self.available_tab = wx.Panel(self.profile_book, -1)
        self.window_2 = wx.SplitterWindow(self.available_tab, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.friends_tab = wx.Panel(self.profile_book, -1)
        self.window_1 = wx.SplitterWindow(self.friends_tab, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.personal_tab = wx.Panel(self.profile_book, -1)
        
        # Menu Bar
        self.profile_menu = wx.MenuBar()
        self.SetMenuBar(self.profile_menu)
        self.profile_item = wx.Menu()
        self.activate_item = wx.MenuItem(self.profile_item, wx.NewId(), _("Activate"), _("Allow users seeing profile"), wx.ITEM_CHECK)
        self.profile_item.AppendItem(self.activate_item)
        self.online_item = wx.MenuItem(self.profile_item, wx.NewId(), _("OnLine"), _("Profile broadcast to peers around"), wx.ITEM_RADIO)
        self.profile_item.AppendItem(self.online_item)
        self.onclick_item = wx.MenuItem(self.profile_item, wx.NewId(), _("OnClick"), _("Profile displayed when peers ask for it"), wx.ITEM_RADIO)
        self.profile_item.AppendItem(self.onclick_item)
        self.onrequest_item = wx.MenuItem(self.profile_item, wx.NewId(), _("OnRequest"), _("Profile available on authorization"), wx.ITEM_RADIO)
        self.profile_item.AppendItem(self.onrequest_item)
        self.profile_item.AppendSeparator()
        self.quit_item = wx.MenuItem(self.profile_item, wx.NewId(), _("Quit"), _("Exit profile management"), wx.ITEM_NORMAL)
        self.profile_item.AppendItem(self.quit_item)
        self.profile_menu.Append(self.profile_item, _("Profile"))
        self.search_item = wx.Menu()
        self.raw_item = wx.MenuItem(self.search_item, wx.NewId(), _("Raw search..."), _("Search profile in surrounding area"), wx.ITEM_NORMAL)
        self.search_item.AppendItem(self.raw_item)
        self.filters_item = wx.MenuItem(self.search_item, wx.NewId(), _("Filters..."), _("Create active filters to get notified on peers approach"), wx.ITEM_NORMAL)
        self.search_item.AppendItem(self.filters_item)
        self.profile_menu.Append(self.search_item, _("Search"))
        # Menu Bar end
        self.profile_statusbar = self.CreateStatusBar(1, 0)
        self.window_3 = solipsis.services.profile.gui.InfoPanel.InfoPanel(self.personal_tab, -1)
        self.list_ctrl_2 = wx.ListCtrl(self.window_1_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.window_4 = solipsis.services.profile.gui.InfoPanel.InfoPanel(self.window_1_pane_2, -1)
        self.list_ctrl_3 = wx.ListCtrl(self.window_2_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.window_5 = solipsis.services.profile.gui.InfoPanel.InfoPanel(self.window_2_pane_2, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ProfileFrame.__set_properties
        self.SetTitle(_("profile_frame"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("/home/emb/svn/solipsis/trunk/main/solipsis/services/profile/images/icon.gif", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((400, 400))
        self.profile_statusbar.SetStatusWidths([-1])
        # statusbar fields
        profile_statusbar_fields = [_("status")]
        for i in range(len(profile_statusbar_fields)):
            self.profile_statusbar.SetStatusText(profile_statusbar_fields[i], i)
        self.profile_book.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ProfileFrame.__do_layout
        frame_sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10.Add(self.window_3, 1, wx.EXPAND, 0)
        self.personal_tab.SetAutoLayout(1)
        self.personal_tab.SetSizer(sizer_10)
        sizer_10.Fit(self.personal_tab)
        sizer_10.SetSizeHints(self.personal_tab)
        sizer_6.Add(self.list_ctrl_2, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetAutoLayout(1)
        self.window_1_pane_1.SetSizer(sizer_6)
        sizer_6.Fit(self.window_1_pane_1)
        sizer_6.SetSizeHints(self.window_1_pane_1)
        sizer_5.Add(self.window_4, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetAutoLayout(1)
        self.window_1_pane_2.SetSizer(sizer_5)
        sizer_5.Fit(self.window_1_pane_2)
        sizer_5.SetSizeHints(self.window_1_pane_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_4.Add(self.window_1, 1, wx.EXPAND, 0)
        self.friends_tab.SetAutoLayout(1)
        self.friends_tab.SetSizer(sizer_4)
        sizer_4.Fit(self.friends_tab)
        sizer_4.SetSizeHints(self.friends_tab)
        sizer_8.Add(self.list_ctrl_3, 1, wx.EXPAND, 0)
        self.window_2_pane_1.SetAutoLayout(1)
        self.window_2_pane_1.SetSizer(sizer_8)
        sizer_8.Fit(self.window_2_pane_1)
        sizer_8.SetSizeHints(self.window_2_pane_1)
        sizer_9.Add(self.window_5, 1, wx.EXPAND, 0)
        self.window_2_pane_2.SetAutoLayout(1)
        self.window_2_pane_2.SetSizer(sizer_9)
        sizer_9.Fit(self.window_2_pane_2)
        sizer_9.SetSizeHints(self.window_2_pane_2)
        self.window_2.SplitVertically(self.window_2_pane_1, self.window_2_pane_2)
        sizer_7.Add(self.window_2, 1, wx.EXPAND, 0)
        self.available_tab.SetAutoLayout(1)
        self.available_tab.SetSizer(sizer_7)
        sizer_7.Fit(self.available_tab)
        sizer_7.SetSizeHints(self.available_tab)
        self.profile_book.AddPage(self.personal_tab, _("Personal"))
        self.profile_book.AddPage(self.friends_tab, _("Friends"))
        self.profile_book.AddPage(self.available_tab, _("Available"))
        frame_sizer.Add(wx.NotebookSizer(self.profile_book), 1, wx.EXPAND, 0)
        self.SetAutoLayout(1)
        self.SetSizer(frame_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class ProfileFrame


