#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Mon Jun 20 17:24:56 2005

import wx

from solipsis.util.wxutils import _
from solipsis.services.profile.gui.ViewerFrame import ViewerFrame

class ViewerApp(wx.App):
    """Top-level class of GUI: application"""
    def __init__(self, options, *args):
        self.options = options
        wx.App.__init__(self, *args)
        
    def OnInit(self):
        wx.InitAllImageHandlers()
        viewer_frame = ViewerFrame(self.options, None, -1, "Profile Viewer")
        self.SetTopWindow(viewer_frame)
        viewer_frame.Show()
        return 1

# end of class ViewerApp

def run():
    """launch editor of profile"""
    import gettext
    gettext.install("viewer") # replace with the appropriate catalog name
    # set options
    options = {}
    options["standalone"] = True
    # launch gui
    editor = ViewerApp(options, 0)
    editor.MainLoop()

    
if __name__ == "__main__":
    run()
