#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Mon Jun 20 17:24:56 2005

from solipsis.util.wxutils import _

from solipsis.services.profile.editor.view import ViewerView
from solipsis.services.profile.gui.ViewerFrame import ViewerFrame
from solipsis.services.profile.gui.base_gui import BaseGUI, get_options

class ViewerApp(BaseGUI):
    """Top-level class of GUI: application"""
    def __init__(self, options, *args):
        BaseGUI.__init__(self, options, *args)
        
    def OnInit(self):
        """overrides"""
        BaseGUI.OnInit(self)
        self.main_window = ViewerFrame(self.options, None,
                                       -1, "Profile Viewer")
        self.SetTopWindow(self.main_window)
        self.main_window.Show()
        # set up facade
        self.facade.add_view(ViewerView(self.facade._desc,
                                        self.main_window))
        return 1

# end of class ViewerApp

def run():
    """launch editor of profile"""
    options = get_options()
    editor = ViewerApp(options, 0)
    editor.MainLoop()
    
if __name__ == "__main__":
    run()
