# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Tue Mar 22 11:28:12 2005

import wx, wx.html
from solipsis.util.uiproxy import UIProxyReceiver

# begin wxGlade: dependencies
# end wxGlade

class MyHtmlWindow(wx.html.HtmlWindow, UIProxyReceiver):
    def __init__(self, *args, **kwds):
        wx.html.HtmlWindow.__init__(self, *args, **kwds)
        UIProxyReceiver.__init__(self)

class PreviewPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PreviewPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.html_preview = MyHtmlWindow(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PreviewPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PreviewPanel.__do_layout
        preview_sizer = wx.BoxSizer(wx.HORIZONTAL)
        preview_sizer.Add(self.html_preview, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(preview_sizer)
        preview_sizer.Fit(self)
        preview_sizer.SetSizeHints(self)
        # end wxGlade

# end of class PreviewPanel
