# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Tue Jun 21 11:01:29 2005

import wx

# begin wxGlade: dependencies
from FileFilterPanel import FileFilterPanel
from PersonalFilterPanel import PersonalFilterPanel
# end wxGlade

class FilterFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FilterFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.filter_book = wx.Notebook(self, -1, style=0)
        
        # Menu Bar
        self.filter_menu = wx.MenuBar()
        self.SetMenuBar(self.filter_menu)
        self.profile_item = wx.Menu()
        self.activate_item = wx.MenuItem(self.profile_item, wx.NewId(), _("&Activated\tCtrl+A"), _("Switch filters on/off"), wx.ITEM_CHECK)
        self.profile_item.AppendItem(self.activate_item)
        self.profile_item.AppendSeparator()
        self.save_item = wx.MenuItem(self.profile_item, wx.NewId(), _("&Save\tCtrl+S"), _("Save profile into file"), wx.ITEM_NORMAL)
        self.profile_item.AppendItem(self.save_item)
        self.quit_item = wx.MenuItem(self.profile_item, wx.NewId(), _("&Close\tCtrl+W"), _("Close profile management"), wx.ITEM_NORMAL)
        self.profile_item.AppendItem(self.quit_item)
        self.filter_menu.Append(self.profile_item, _("Action"))
        self.help_menu = wx.Menu()
        self.about_item = wx.MenuItem(self.help_menu, wx.NewId(), _("About..."), "", wx.ITEM_NORMAL)
        self.help_menu.AppendItem(self.about_item)
        self.filter_menu.Append(self.help_menu, _("Help"))
        # Menu Bar end
        self.filter_statusbar = self.CreateStatusBar(1, 0)
        self.personal_filter_tab = PersonalFilterPanel(self.filter_book, -1)
        self.file_filter_tab = FileFilterPanel(self.filter_book, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FilterFrame.__set_properties
        self.SetTitle(_("Profile Filters"))
        self.SetSize((460, 749))
        self.filter_statusbar.SetStatusWidths([-1])
        # statusbar fields
        filter_statusbar_fields = [_("status")]
        for i in range(len(filter_statusbar_fields)):
            self.filter_statusbar.SetStatusText(filter_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FilterFrame.__do_layout
        frame_sizer = wx.BoxSizer(wx.VERTICAL)
        self.filter_book.AddPage(self.personal_filter_tab, _("Personal"))
        self.filter_book.AddPage(self.file_filter_tab, _("Files"))
        frame_sizer.Add(self.filter_book, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(frame_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class FilterFrame


