#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Tue Jun 21 11:01:29 2005

import wx
from FilterFrame import FilterFrame

class FilterApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        filter_frame = FilterFrame(None, -1, "")
        self.SetTopWindow(filter_frame)
        filter_frame.Show()
        return 1

# end of class FilterApp

if __name__ == "__main__":
    import gettext
    gettext.install("filter") # replace with the appropriate catalog name

    filter = FilterApp(0)
    filter.MainLoop()
